apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: votingapp
  namespace: votingapp
spec:
  interval: 5m
  chart:
    spec:
      chart: ./votingapp
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    replicaCount: 1