apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: votingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: shristi19/votingapp-result:latest
          ports:
            - containerPort: 5001
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: votingapp
spec:
  type: ClusterIP
  selector:
    app: result
  ports:
    - port: 5001
      targetPort: 5001